### ISSUE TITLE
请问一下大佬，java.lang.NoClassDefFoundError 该怎么办

### ISSUE THREAD

**Issue by fy0** [Siy-Wu/ExcludeAar#14]
我通过在dependence里面增加这样的配置，剔除掉了重复的部分：
```

    excludePluginExt {
        autoDependencies = true
        aars {
            "VGame-Core-1220" {
                path "/libs/exclude/VGame-Core-1220.aar"
                excludePackages 'com.ss.android.a', 'com.ss.android.download', 'com.ss.android.downloadad', 'com.ss.android.downloadlib', 'com.ss.android.socialbase'
            }
        }
    }
```

然后编译成功了，运行时候失败，请问有什么办法可以搞定呢？

```
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/ss/android/downloadlib/addownload/GlobalInfo;
        at com.ss.union.game.sdk.common.download.GameDownloadManager.doInit(SourceFile:154)
        at com.ss.union.game.sdk.core.base.init.GameSdkCoreInit.init(SourceFile:69)
        at com.ss.union.game.sdk.core.base.init.a.f.doIt(SourceFile:17)
```

**Comment by ssiyy** [comment]
这个类GlobalInfo运行时候需要，你不因该删除它。你可以采用excludeClasses排除除了这个类以外的其它类




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Siy-Wu/ExcludeAar"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月29日(星期五) 下午3:42
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[Siy-Wu/ExcludeAar] 请问一下大佬，java.lang.NoClassDefFoundError 该怎么办 (Issue #14)





 
我通过在dependence里面增加这样的配置，剔除掉了重复的部分：
      excludePluginExt {         autoDependencies = true         aars {             "VGame-Core-1220" {                 path "/libs/exclude/VGame-Core-1220.aar"                 excludePackages 'com.ss.android.a', 'com.ss.android.download', 'com.ss.android.downloadad', 'com.ss.android.downloadlib', 'com.ss.android.socialbase'             }         }     }  
然后编译成功了，运行时候失败，请问有什么办法可以搞定呢？
 java.lang.NoClassDefFoundError: Failed resolution of: Lcom/ss/android/downloadlib/addownload/GlobalInfo;         at com.ss.union.game.sdk.common.download.GameDownloadManager.doInit(SourceFile:154)         at com.ss.union.game.sdk.core.base.init.GameSdkCoreInit.init(SourceFile:69)         at com.ss.union.game.sdk.core.base.init.a.f.doIt(SourceFile:17)  
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by fy0** [comment]
不行……但凡有一个类暴露出来，都会报 Duplicate class

这会不会跟加载顺序有关？有无办法将这个包的引用重定向到另一个arr？

**Comment by fy0** [comment]
……对方发了我一个测试版本，解决了冲突问题
